---
pipeline:

  step1:
    image: alpine:tput
      
    #commands:
    #  - echo $${AUTH_TOKEN} $${MY_NAME}
    #  - echo $${PLUGIN_CMDS}

  #step2:
   # image: gradle:v01
    #commands:
    #  - echo $${AUTH_TOKEN}
