---
pipeline:

  restore_cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.gradle
    volumes:
      - /tmp/cache:/cache

  step1:
    image: gradle:v01
    commands:
      - echo this is step 1
      - gradle -g $${DRONE_WORKSPACE}/.gradle build

  step2:
    image: gradle:v01
    commands:
      - echo this is step 2
      - gradle -g $${DRONE_WORKSPACE}/.gradle  build

  rebuild_cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.gradle
    volumes:
      - /tmp/cache:/cache
