---
pipeline:

  step1:
    image: gradle:v01
    secrets: [auth_token, my_name]
    commands:
      - echo $${AUTH_TOKEN} $${MY_NAME}

  step2:
    image: gradle:v01
    commands:
      - echo $${AUTH_TOKEN}
